//@version=5
indicator("Equal Highs and Lows Line Drawer", shorttitle="Levels", overlay=true, max_bars_back=960)

checkRange = input.int(10, title="Check Range", minval=0)
luft = input.float(0.01, title="Luft", minval=0, step=0.01)
touches = input.int(4, title="Touches", minval=2)
exactTouches = input.int(2, title="Exact Touches", minval=0)
numberOfLevels = input.int(5, title="Number of Levels", minval=1)

var float[] highs = array.new_float()
var float[] lows = array.new_float()
var line[] lines = array.new_line()
var label[] labels = array.new_label()

shouldDrawLine(priceLevel) =>
    countLuft = 0
    countExact = 0
    for i = 0 to array.size(highs) - 1
        if math.abs(array.get(highs, i) - priceLevel) <= luft
            countLuft := countLuft + 1
        if array.get(highs, i) == priceLevel
            countExact := countExact + 1
    for i = 0 to array.size(lows) - 1
        if math.abs(array.get(lows, i) - priceLevel) <= luft
            countLuft := countLuft + 1
        if array.get(lows, i) == priceLevel
            countExact := countExact + 1
    (luft > 0 and countExact >= exactTouches and countLuft >= touches) or (luft == 0 and countLuft >= touches)

countHighTouches(priceLevel) =>
    count = 0
    for i = 0 to array.size(highs) - 1
        if math.abs(array.get(highs, i) - priceLevel) <= luft
            count := count + 1
    count

countLowTouches(priceLevel) =>
    count = 0
    for i = 0 to array.size(lows) - 1
        if math.abs(array.get(lows, i) - priceLevel) <= luft
            count := count + 1
    count

drawLine(priceLevel, lineColor, style) =>
    // Remove the oldest line if we exceed the number of levels
    if array.size(lines) == numberOfLevels
        line.delete(array.shift(lines))
    l = line.new(bar_index - 40, priceLevel, bar_index, priceLevel, color=lineColor, style = style, width=1)
    array.push(lines, l)

drawLabel(priceLevel, value, color, shift) =>
    if array.size(labels) == numberOfLevels
        label.delete(array.shift(labels))
    l = label.new(bar_index, priceLevel+shift, str.tostring(value,'#') +  str.tostring(priceLevel,'/#.##'), textcolor = color, style = label.style_none)    
    array.push(labels, l)

mostTouched(countMore, countLess, isLimit) =>
    countMore > 0 and (countLess == 0 or countLess/countMore <= 0.8) and isLimit


array.push(highs, high)
array.push(lows, low)

if (array.size(highs) > checkRange)
    array.shift(highs)
    array.shift(lows)

// Check for matching highs and lows and draw a line
if (array.size(highs) > 0)
    colorHigh = color.blue
    colorLow = colorHigh
    style = line.style_dashed
    drawHigh = shouldDrawLine(high)
    drawLow = shouldDrawLine(low)
    HH = countHighTouches(high)
    LH = countLowTouches(high)
    HL = countHighTouches(low)
    LL = countLowTouches(low)
    if (mostTouched(HH, LH, drawHigh))
        colorHigh := color.red
        style := line.style_solid
    if (mostTouched(LH, HH, drawHigh))
        colorHigh := color.green
        style := line.style_solid
    if (mostTouched(LL, HL, drawLow))
        colorLow := color.green
        style := line.style_solid
    if (mostTouched(HL, LL, drawLow))
        colorLow := color.red
        style := line.style_solid
     
    if drawHigh
        drawLine(high, colorHigh, style)
       // drawLabel(high, (exHH+exLH), color, 0.02)
    if drawLow
        drawLine(low, colorLow, style)
       // drawLabel(low, (exHL+exLL), color, -0.02)//@version=5
indicator("Equal Highs and Lows Line Drawer", shorttitle="Levels", overlay=true, max_bars_back=960)

checkRange = input.int(10, title="Check Range", minval=0)
luft = input.float(0.01, title="Luft", minval=0, step=0.01)
touches = input.int(4, title="Touches", minval=2)
exactTouches = input.int(2, title="Exact Touches", minval=0)
numberOfLevels = input.int(5, title="Number of Levels", minval=1)

var float[] highs = array.new_float()
var float[] lows = array.new_float()
var line[] lines = array.new_line()
var label[] labels = array.new_label()

shouldDrawLine(priceLevel) =>
    countLuft = 0
    countExact = 0
    for i = 0 to array.size(highs) - 1
        if math.abs(array.get(highs, i) - priceLevel) <= luft
            countLuft := countLuft + 1
        if array.get(highs, i) == priceLevel
            countExact := countExact + 1
    for i = 0 to array.size(lows) - 1
        if math.abs(array.get(lows, i) - priceLevel) <= luft
            countLuft := countLuft + 1
        if array.get(lows, i) == priceLevel
            countExact := countExact + 1
    (luft > 0 and countExact >= exactTouches and countLuft >= touches) or (luft == 0 and countLuft >= touches)

countHighTouches(priceLevel) =>
    count = 0
    for i = 0 to array.size(highs) - 1
        if math.abs(array.get(highs, i) - priceLevel) <= luft
            count := count + 1
    count

countLowTouches(priceLevel) =>
    count = 0
    for i = 0 to array.size(lows) - 1
        if math.abs(array.get(lows, i) - priceLevel) <= luft
            count := count + 1
    count

drawLine(priceLevel, lineColor, style) =>
    // Remove the oldest line if we exceed the number of levels
    if array.size(lines) == numberOfLevels
        line.delete(array.shift(lines))
    l = line.new(bar_index - 40, priceLevel, bar_index, priceLevel, color=lineColor, style = style, width=1)
    array.push(lines, l)

drawLabel(priceLevel, value, color, shift) =>
    if array.size(labels) == numberOfLevels
        label.delete(array.shift(labels))
    l = label.new(bar_index, priceLevel+shift, str.tostring(value,'#') +  str.tostring(priceLevel,'/#.##'), textcolor = color, style = label.style_none)    
    array.push(labels, l)

mostTouched(countMore, countLess, isLimit) =>
    countMore > 0 and (countLess == 0 or countLess/countMore <= 0.8) and isLimit


array.push(highs, high)
array.push(lows, low)

if (array.size(highs) > checkRange)
    array.shift(highs)
    array.shift(lows)

// Check for matching highs and lows and draw a line
if (array.size(highs) > 0)
    colorHigh = color.blue
    colorLow = colorHigh
    style = line.style_dashed
    drawHigh = shouldDrawLine(high)
    drawLow = shouldDrawLine(low)
    HH = countHighTouches(high)
    LH = countLowTouches(high)
    HL = countHighTouches(low)
    LL = countLowTouches(low)
    if (mostTouched(HH, LH, drawHigh))
        colorHigh := color.red
        style := line.style_solid
    if (mostTouched(LH, HH, drawHigh))
        colorHigh := color.green
        style := line.style_solid
    if (mostTouched(LL, HL, drawLow))
        colorLow := color.green
        style := line.style_solid
    if (mostTouched(HL, LL, drawLow))
        colorLow := color.red
        style := line.style_solid
     
    if drawHigh
        drawLine(high, colorHigh, style)
       // drawLabel(high, (exHH+exLH), color, 0.02)
    if drawLow
        drawLine(low, colorLow, style)
       // drawLabel(low, (exHL+exLL), color, -0.02)